# Question 12

In [2]:
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg

img = mpimg.imread('dog.jpeg')

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 15.0MB/s]


In [3]:
gray_img_01 = (img.min(axis=2, keepdims=True) + img.max(axis=2, keepdims=True)) / 2
gray_img_01[0, 0]

array([102.5])

# Question 13:

In [4]:
gray_img_02 = img.mean(axis=2, keepdims=True)
gray_img_02[0, 0]

array([107.66666667])

# Question 14:

In [5]:
gray_img_03 = img[:, :, 0] * 0.21 + img[:, :,1] * 0.72 + img[:, :, 2] * 0.07
gray_img_03[0, 0]

126.22999999999999

# Question 15:

In [6]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('advertising.csv')

data = df.to_numpy()

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 17.7MB/s]


In [7]:
data

array([[230.1,  37.8,  69.2,  22.1],
       [ 44.5,  39.3,  45.1,  10.4],
       [ 17.2,  45.9,  69.3,  12. ],
       [151.5,  41.3,  58.5,  16.5],
       [180.8,  10.8,  58.4,  17.9],
       [  8.7,  48.9,  75. ,   7.2],
       [ 57.5,  32.8,  23.5,  11.8],
       [120.2,  19.6,  11.6,  13.2],
       [  8.6,   2.1,   1. ,   4.8],
       [199.8,   2.6,  21.2,  15.6],
       [ 66.1,   5.8,  24.2,  12.6],
       [214.7,  24. ,   4. ,  17.4],
       [ 23.8,  35.1,  65.9,   9.2],
       [ 97.5,   7.6,   7.2,  13.7],
       [204.1,  32.9,  46. ,  19. ],
       [195.4,  47.7,  52.9,  22.4],
       [ 67.8,  36.6, 114. ,  12.5],
       [281.4,  39.6,  55.8,  24.4],
       [ 69.2,  20.5,  18.3,  11.3],
       [147.3,  23.9,  19.1,  14.6],
       [218.4,  27.7,  53.4,  18. ],
       [237.4,   5.1,  23.5,  17.5],
       [ 13.2,  15.9,  49.6,   5.6],
       [228.3,  16.9,  26.2,  20.5],
       [ 62.3,  12.6,  18.3,   9.7],
       [262.9,   3.5,  19.5,  17. ],
       [142.9,  29.3,  12.6,  15. ],
 

In [8]:
max_index = data[:, [3]].argmax()
max_value = data[:, [3]][max_index][0]
print(f'Max value: {max_value}, Max index: {max_index}')

Max value: 27.0, Max index: 175


# Question 16:

In [9]:
tv_mean = data[:, [0]].mean()
print(f'Mean of TV column: {tv_mean}')

Mean of TV column: 147.0425


# Question 17:

In [10]:
sale_data = data[:, 3]
counts = len(sale_data[sale_data >= 20])
print(f'Count: {counts}')

Count: 40


# Question 18:

In [11]:
value = data[data[:, 3] >= 15][:, 1].mean()
print(f'Mean in Radio where Sales greater than 15: {value}')

Mean in Radio where Sales greater than 15: 26.22293577981651


# Question 19:

In [12]:
newspaper_mean = data[:, [2]].mean()
total = data[data[:, 2] > newspaper_mean][:, 3].sum()
print(f'Total Sales: {total}')

Total Sales: 1405.1


# Question 20:

In [20]:
import numpy as np

sales_df = data[:, 3]
sales_mean = sales_df.mean()
scores = np.full(shape=sales_df.shape, fill_value='Average')

scores[sales_df > sales_mean] = "Good"
scores[sales_df < sales_mean] = "Bad"

scores[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U7')